# Generated by Django 3.1.7 on 2021-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
    ]
